In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

A = torch.tensor([
    [0, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 1, 0],
    [0, 1, 2, 2, 1, 0],
    [0, 1, 2, 2, 1, 0],
    [0, 1, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

B = torch.tensor([
    [0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1],
    [2, 2, 1, 1, 2, 2],
    [2, 2, 1, 1, 2, 2],
    [1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0],
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)


class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 1, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(1, 1, kernel_size=3, padding=1)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.conv2(x)
        return x

model = ConvNet()
optimizer = optim.Adam(model.parameters(), lr=0.01)
epochs = 500
for epoch in range(epochs):
    optimizer.zero_grad()
    output = model(A)
    loss = F.mse_loss(output, B)
    loss.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print(f'Epoch {epoch}: loss = {loss.item()}')

final_output = model(A)
print("Final output without rounding:\n", final_output)
rounded_output = torch.round(final_output)
print("Final rounded output:\n", rounded_output)


Epoch 0: loss = 0.9401260018348694
Epoch 100: loss = 0.18587777018547058
Epoch 200: loss = 0.09854262322187424
Epoch 300: loss = 0.02536400593817234
Epoch 400: loss = 0.007136618718504906
Final output without rounding:
 tensor([[[[-0.0441, -0.0021,  0.0406,  0.0207, -0.0232, -0.0294],
          [ 1.0941,  1.0192,  0.9437,  0.9431,  1.0114,  1.0801],
          [ 1.9932,  1.9659,  1.0456,  1.0798,  1.9788,  1.9712],
          [ 1.8831,  1.9454,  1.0537,  1.0172,  1.9469,  1.9224],
          [ 1.1610,  1.1030,  0.9275,  0.9337,  1.0906,  1.1240],
          [-0.0638, -0.0222, -0.0462, -0.0359, -0.0133, -0.0866]]]],
       grad_fn=<ConvolutionBackward0>)
Final rounded output:
 tensor([[[[-0., -0., 0., 0., -0., -0.],
          [1., 1., 1., 1., 1., 1.],
          [2., 2., 1., 1., 2., 2.],
          [2., 2., 1., 1., 2., 2.],
          [1., 1., 1., 1., 1., 1.],
          [-0., -0., -0., -0., -0., -0.]]]], grad_fn=<RoundBackward0>)


In [12]:
B

tensor([[[[0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1.],
          [2., 2., 1., 1., 2., 2.],
          [2., 2., 1., 1., 2., 2.],
          [1., 1., 1., 1., 1., 1.],
          [0., 0., 0., 0., 0., 0.]]]])